### PR TITLE
market candles endpoint

### PR DESCRIPTION
**Pull request by ngauthier**
New market candles endpoint. Going to beta test this on nomics.com before general release.

### CODE REVIEW

**Comment by ngauthier** [comment]
@claycollins preview of Market Pair Candles paid endpoint: https://nomics-api-docs-pr-19.herokuapp.com/#operation/getMarketCandles

**Comment by ngauthier** [comment]
I tried, but unfortunately you can't re-use the same section name across section groups. I can look into it more though. The docs are pretty light on this grouping extension we're using for the Commercial section.

**Comment by claycollins** [comment]
@ngauthier I'm good with a cheap hack, like changing the section name to "Candles_" or "Candles " to avoid the duplication.

**Comment by ngauthier** [comment]
I had an idea to put an asterisk on the commercial tags. This allows us to easily group separately, and also I think it's a nice way to do it because it implies the asterisk is for commercial. That OK?

https://nomics-api-docs-pr-19.herokuapp.com/

**Comment by ngauthier** [comment]
Clay gave this 👍 in trello.

**Pull request merged**
