### PR TITLE
spec: add `num_pairs_unmapped' to currencies ticker

### PR DESCRIPTION
**Pull request by Bogdanp**

### CODE REVIEW

**Comment by Bogdanp** [comment]
[Unmapped markets tab for asset page](https://trello.com/c/eagQDIq0/1198-unmapped-markets-tab-for-asset-page)

**Comment by Bogdanp** [comment]
@spencewood looks like this is being held up by Heroku CI. I didn't follow the netlify transition very closely. Should that check be dropped? It's required so I can't merge if it doesn't pass.

**Comment by spencewood** [comment]
@Bogdanp I just disabled automatic deploys on Heroku for this along with "Wait for CI to pass before deploy". I think that should do it. We don't need any of the heroku pipeline for this anymore. I think we need to have a new commit or reopen this PR to reset status.

The changes are here: https://deploy-preview-124--nomics-docs.netlify.app/

**Comment by Bogdanp** [comment]
Thanks! I just re-did the commit and force-pushed, but it still says "Required". I'll try a new PR.

**Pull request closed without merging**
