### PR TITLE
Adding a community projects section

### PR DESCRIPTION
**Pull request by harrisonbrandon**

### CODE REVIEW

**Comment by harrisonbrandon** [comment]
@trestrantham how can I get this deployment active again? Clay is able to get around to reviewing this but I need a new link. #newbie

**Comment by trestrantham** [comment]
You go to Pipeline page on Heroku and click Create Review App here: https://dashboard.heroku.com/pipelines/6c0fdf65-bddc-446c-8814-11f54f60271f

I've went ahead and did it for this one. The review apps only live for 5 days at a time. You'll have to re-create them for longer running ones.

**Comment by harrisonbrandon** [comment]
@trestrantham ok, cool. I don't I have access to Heroku so I'll ask Nick about that. Thanks for doing this!

@ngauthier would I be able to access heroku so I can re-create review apps that expire? Otherwise, I can always just reach out to one of you all depending on the project. This is only the second time this has happened in a few months so not too critical.

**Comment by ngauthier** [comment]
I've invited you. This is the page you need to be able to access:

https://dashboard.heroku.com/pipelines/6c0fdf65-bddc-446c-8814-11f54f60271f

From there you can see "Create Review App" buttons for PRs.

**Comment by harrisonbrandon** [comment]
Thanks @ngauthier! I'm in and this looks great.

**Comment by harrisonbrandon** [comment]
@trestrantham thanks! Glad you can review these now :) Sorry to bug you, Nick!

**Comment by ngauthier** [comment]
No worries. I didn't have much availability this morning, didn't want to
hold it up. But yeah, Tres can be the #1 for these reviews.

**Comment by harrisonbrandon** [comment]
@ngauthier appreciate that! I'll definitely hit Tres up first on these now 👍 Thanks again!

**Pull request merged**
