### PR TITLE
currency ticker ids and convert params, id and symbol fields

### PR DESCRIPTION
**Pull request by ngauthier**
- currency ticker:
  - adds `ids` parameter
  - adds `convert` parameter
  - deprecates `quote-currency` parameter
  - adds `id` field
  - adds `symbol` field
  - deprecates `currency` field
- deprecates `prices`
- deprecates `dashboard`
- deprecates `currencies interval`
- deprecates `all time highs`
- renames `currencies` to `currencies metadata`

### CODE REVIEW

**Comment by ngauthier** [comment]
@spencewood new currency ticker features and deprecations. Can you bring these changes through to the nomics javascript client?

**Comment by ngauthier** [comment]
[Currency ticker SQL + last price (beyond a year)](https://trello.com/c/YK110PaM/418-currency-ticker-sql-last-price-beyond-a-year)

**Comment by ngauthier** [comment]
@claycollins @spencewood @trestrantham did some heavy cleanup and deprecation around the currency ticker. This sound good to everyone?

@spencewood are you still using any of the endpoints I deprecated?

**Comment by spencewood** [comment]
I'll get to the javascript client updates when I can. If there is an active card for this, assign it to me and I'll make the updates.

The web code is still using the prices endpoint to create the currencies sitemap and it is still using currencies interval to compile a list of "exchange rates" (used on all markets tables, and currency pair pages). Both of these I want to get away from, the latter requiring some new tickers to replace what is being derived by nomics.com currently.

**Comment by ngauthier** [comment]
Thanks. I wanted to make sure there weren't any that you felt should stay. I'll make a card for the javascript client.

**Comment by spencewood** [comment]
Oh yeah, and one more: `/v1/currencies/highs`. If that is the ATH endpoint, that is still being used too for the pair page. I want to move away from this too in favor of a ticker. I just want to make sure these won't vanish any time soon!

**Comment by ngauthier** [comment]
They absolutely won't be removed without a major version change.
Deprecation is to help users find the newer and better endpoints more
clearly.

**Comment by ngauthier** [comment]
By the way, you can now use the ticker in a very minimal mode:

https://api.nomics.com/v1/currencies/ticker?key=2018-09-demo-dont-deploy-b69315e440beb145&ids=BTC,ETH&interval=false&convert=EUR

Might be helpful for the pair page.

**Comment by trestrantham** [comment]
Wow that's awesome to get arbitrary `ids` like that with ranking. I wonder now that we're in SQL if it would be too much to add the delta ranks directly in the ticker. Possibly where every interval has it's own rank so @spencewood doesn't need to do all that on Nomics backend.

**Comment by spencewood** [comment]
> By the way, you can now use the ticker in a very minimal mode:
> 
> https://api.nomics.com/v1/currencies/ticker?key=2018-09-demo-dont-deploy-b69315e440beb145&ids=BTC,ETH&interval=false&convert=EUR
> 
> Might be helpful for the pair page.

Yeah that will be really helpful. There is some code I can cut out in a few places because of this!

**Comment by ngauthier** [comment]
> Wow that's awesome to get arbitrary `ids` like that with ranking. I wonder now that we're in SQL if it would be too much to add the delta ranks directly in the ticker. Possibly where every interval has it's own rank so @spencewood doesn't need to do all that on Nomics backend.

Yeah this sort of thing will be much easier to move over now.

**Pull request merged**
