### PR TITLE
Header & footer updates

### PR DESCRIPTION
**Pull request by harrisonbrandon**
**Header**
- Swapping "currencies" to "cryptocurrency list"

**Footer**
- Swapping "currencies" to "cryptocurrency list"
- Add "Crypto Market Cap" essay to footer under "learn"
- Get rid of ID for headway link in footer
- Changed “mr2-l” to “mr3-l” for more footer space
- Change purple heart to hsla(280, 100%, 50%, 1)

### CODE REVIEW

**Comment by harrisonbrandon** [comment]
Thanks @spencewood! I forgot Tres is on PTO. Are you able to merge it? Otherwise, I'll ask Nick since I need to ask him about being able to do this myself anyways, haha.

**Comment by spencewood** [comment]
Doesn't look like I can...

**Comment by harrisonbrandon** [comment]
All good @spencewood!

@ngauthier would I be able to get access so that I can merge PR's from here like I can on Nomics.com? That way I'm not held up when Tres is on PTO or so I don't have to bug people for easy stuff like this either :) If there's a reason you don't want it set up that way, I totally respect that and don't mind asking. I'm assuming it's not intentional though so figured I should ask. Either way, please let me know. Thanks a ton!

**Comment by ngauthier** [comment]
Cool! You had permission, but since Tyler wasn't on the repo, his review didn't count. So I added him and now it's good to go. Let me know if you can't merge now.

**Comment by harrisonbrandon** [comment]
@ngauthier oh, perfect! I can merge. Thank you 🙌

**Pull request merged**
