### PR TITLE
Specify update frequency for candles

### PR DESCRIPTION
**Pull request by trestrantham**

### CODE REVIEW

**Comment by trestrantham** [comment]
@ngauthier Are the `5m` candles updated exactly at 50s (5m/6) or closer to 1m (which is what I put here)?

**Comment by trestrantham** [comment]
[API Docs - Disclaimer about potential candle delays?](https://trello.com/c/DA5IvIKO/274-api-docs-disclaimer-about-potential-candle-delays)

**Comment by ngauthier** [comment]
Hey Tres, so unfortunately this has changed since I wrote the trello card. Exchange candles are updated as often as possible, but at most every 10s for 1m and 5m candles, and at most 1m for larger sizes.

Aggregate candles are still every 1/6 interval.

**Comment by ngauthier** [comment]
Also, the aggregated candles are updated more frequently than that:

https://github.com/nomics-crypto/nommer/blob/master/refresh/refresher.go#L37-L65

1h every 5 mins, and 1d every 2h. And I'm actually considering reducing that a lot since I'm been making some big performance improvements on the database. But you can put that for now and I'll change it if I change things.

**Comment by trestrantham** [comment]
Updated 😎

**Comment by ngauthier** [comment]
Thanks! But of course I love to be a pain in the butt so I actually changed the update frequency of aggregated 1d candles to 15 minutes on Friday 😅

**Comment by trestrantham** [comment]
Once more with feeling 😅

**Pull request merged**
