### PR TITLE
Add JavaScript examples and rename existing to NodeJS

### PR DESCRIPTION
**Pull request by trestrantham**

### CODE REVIEW

**Comment by ngauthier** [comment]
Thanks! Could you do the same format for the NodeJS example? I like how you formatted the JS calls (line by line like that).

**Comment by trestrantham** [comment]
Done!

**Comment by ngauthier** [comment]
:shipit:

**Comment by trestrantham** [comment]
Looks like you'll need to approve this before I can merge

**Comment by ngauthier** [comment]
oh strange I didn't have a button at the top. Sorry!

**Pull request merged**
