### PR TITLE
exchange markets ticker

### PR DESCRIPTION
**Pull request by ngauthier**
1. Adds exchange markets ticker
2. Deprecates Exchange Rates Interval (no other interval endpoints are not deprecated, so they don't need conversion)
3. Deprecates Market Prices
4. Deprecates Market Interval
5. Deprecates Exchange Market Prices
6. Deprecates Exchange Market Interval

### CODE REVIEW

**Comment by ngauthier** [comment]
@claycollins just wanted to FYI you here that this is the last ticker for functionality we already had available, so now all interval endpoints are deprecated!

**Comment by ngauthier** [comment]
@spencewood want to double check if there's anything else you're not using that we could deprecate?

**Comment by ngauthier** [comment]
[Exchange Markets Ticker](https://trello.com/c/d9FIonh9/316-exchange-markets-ticker)

**Comment by spencewood** [comment]
It looks like this covers it! As I was double checking over these, I did find a single use of exchange market interval in the nomics.com code base. It is used to generate the markets.xml sitemap. I can switch this over to use a ticker, but it is likely to be horrendously slow. Right now it generates a single pair for each currency where the quote represents the highest volume. As long as this API is just "deprecated" but won't go away any time soon, I can address this later.

**Comment by ngauthier** [comment]
Oh yeah, good point. Yeah we won't shut down deprecated endpoints without a lot more notice and thoroughness. In the future I want to allow hitting the exchange markets ticker for all markets and have it be quick.

**Pull request merged**
